INSERT INTO avia_company VALUES
                             (1, 'Smartavia (Смартавиа)', '', '5N', null),
                             (2, 'Авиалинии Дагестана (Dagestan Airlines)', '', 'N2', null),
                             (3, 'Авиалинии Мордовии (Mordovia Airlines)', '', '', null),
                             (4, 'Авиалинии Саудовской Аравии (Saudi Arabian Airlines)', '', 'SV', null),
                             (5, 'Авиалинии Харькова (Kharkiv Airlines)', '', 'KT', null),
                             (6, 'Авиалинии Шри-Ланки (SriLankan Airlines)', '', 'UL', null),
                             (7, 'Авианка (Avianca Airlines)', '', 'AV', null),
                             (8, 'Авианова (Avianova)', '', 'AO', null),
                             (9, 'АвиаТрафик Компани (Avia Traffic Company)', '', 'YK', null),
                             (10, 'Аврора (Aurora)', '', 'HZ', null),
                             (11, 'Австрийские авиалинии (Austrian Airlines)', '', 'OS', null),
                             (12, 'Адрия Эйрвэйс (Adria Airways)', '', 'JP', null),
                             (13, 'АЗАЛ - Азербайджанские Авиалинии (AZAL - Azerbaijan Airlines)', '', 'J2', null),
                             (14, 'Азиана Эйрлайнс (Asiana Airlines)', '', 'OZ', null),
                             (15, 'Азимут (Azimuth)', '', 'A4', null),
                             (16, 'Азур Эйр (Azur Air)', '', 'ZF', null),
                             (17, 'Азур Эйр Украина (Azur Air Ukraine)', '', 'QU', null),
                             (18, 'Ай Флай (I Fly)', '', 'I4', null),
                             (19, 'Айслэндэйр (Icelandair)', '', 'FI', null),
                             (20, 'АК Алроса (Alrosa Airlines)', '', '6R', null),
                             (21, 'АК БАРС АЭРО (Ak Bars Aero)', '', '2B', null),
                             (22, 'Алиталия (Alitalia)', '', 'AZ', null),
                             (23, 'АльМарсия Юниверсал Эйрлайнс (AlMasria Universal Airlines)', '', 'UJ', null),
                             (24, 'Аляска Эйрлайнс (Alaska Airlines)', '', 'AS', null),
                             (25, 'Американ Эйрлайнс (American Airlines)', '', 'AA', null),
                             (26, 'Анадолу Джет (AnadoluJet)', '', 'TK', null),
                             (27, 'Ангара (Angara Airlines)', '', '2G', null),
                             (28, 'Анда Эйр (Anda Air)', '', '5G', null),
                             (29, 'АП (UP)', '', 'LY', null),
                             (30, 'Аргентинские Авиалинии (Aerolineas Argentinas)', '', 'AR', null),
                             (31, 'Аркиа Израильские авиалинии (Arkia Israeli Airlines)', '', 'IZ', null),
                             (32, 'Армавиа (Armavia Airline)', '', 'U8', null),
                             (33, 'Астра Эйрлайнс (Astra Airlines)', '', '', null),
                             (34, 'Атлас Глобал (Atlas Global)', '', 'KK', null),
                             (35, 'Атласджет Украина (Atlasjet Ukraine)', '', 'UH', null),
                             (36, 'Атласджет Эйрлайнс (Atlasjet Airlines)', '', 'KK', null),
                             (37, 'Аэр Лингус (Aer Lingus)', '', 'EI', null),
                             (38, 'Аэромексика (Aeromexico)', '', 'AM', null),
                             (39, 'АэроСвит (AeroSvit Airlines)', '', 'VV', null),
                             (40, 'Аэросервис (Aeroservice)', '', '', null),
                             (41, 'Аэрофлот - Российские авиалинии (Aeroflot Russian Airlines)', '', 'SU', null),
                             (42, 'АэроЮнион (AeroUnion)', '', '6R', null),
                             (43, 'Бангкок Эйрвэйс (Bangkok Airways)', '', 'PG', null),
                             (44, 'Бек Эйр (Bek Air)', '', 'Z9', null),
                             (45, 'Белавиа (Belavia Airlines)', '', 'B2', null),
                             (46, 'Бинтер Канариас (Binter Canarias)', '', 'NT', null),
                             (47, 'БиЭйч Эйр (BH Air)', '', '1B', null),
                             (48, 'БиЭмАй (BMI Airlines)', '', 'BD', null),
                             (49, 'Блу Берд Эйрвэйс (Blue Bird Airways)', '', 'BZ', null),
                             (50, 'Блу Ван (Blue1)', '', 'KF', null),
                             (51, 'Блу Экспресс (Blu Express)', '', 'BV', null),
                             (52, 'Блю Панорама Эйрлайнс (Blue Panorama Airlines)', '', 'BV', null),
                             (53, 'Болгария Эйр (Bulgaria Air)', '', 'FB', null),
                             (54, 'Браво Эйрвейз (Bravo Airways)', '', '', null),
                             (55, 'Бритиш Эйрвейз (British Airways)', '', 'BA', null),
                             (56, 'Брюссельские Авиалинии (Brussels Airlines)', '', 'SN', null),
                             (57, 'Бурятские авиалинии (Buryat Airlines)', '', 'BU', null),
                             (58, 'Былина (Bylina)', '', '', null),
                             (59, 'Бюджетный перевозчик (BudgetAirline)', '', 'DP', null),
                             (60, 'Вест Джет (WestJet Airlines)', '', 'WS', null),
                             (61, 'ВизЭйр (WizzAir)', '', 'W6', null),
                             (62, 'ВизЭйр Украина (WizzAir Ukraine)', '', 'WU', null),
                             (63, 'ВИМ-АВИА (VIM Airlines)', '', 'NN', null),
                             (64, 'Винд Джет (Wind Jet)', '', 'IV', null),
                             (65, 'Вирджин Австралия (Virgin Australia)', '', 'VA', null),
                             (66, 'Вирджин Америка (Virgin America)', '', 'VX', null),
                             (67, 'Вирджин Атлантик Эйрвэйс (Virgin Atlantic Airways)', '', 'VS', null),
                             (68, 'Владивосток Авиа (Vladivostok Air) Владавиа', '', 'XF', null),
                             (69, 'Волга-Днепр (Volga-Dnepr)', '', 'VI', null),
                             (70, 'Волотеа (Volotea)', '', 'V7', null),
                             (71, 'Вьет Джет (VietJet Air)', '', 'VJ', null),
                             (72, 'Вьетнамские авиалинии (Vietnam Airlines)', '', 'VN', null),
                             (73, 'Вьюлинг (Vueling Airlines)', '', 'VY', null),
                             (74, 'Вэльюэйр (Valuair)', '', 'VF', null),
                             (75, 'Гавайские авиалинии (Hawaiian Airlines)', '', 'HA', null),
                             (76, 'Газпромавиа (Gazpromavia)', '', '4G', null),
                             (77, 'Галф Эйр (Gulf Air)', '', 'GF', null),
                             (78, 'Гамбург Эйрвейз (Hamburg Airways)', '', 'HK', null),
                             (79, 'Гаруда Индонезия (Garuda Indonesia Airways)', '', 'GA', null),
                             (80, 'Германия Эйрлайнс (Germania Airlines)', '', 'ST', null),
                             (81, 'Глобус (Globus)', '', 'GB', null),
                             (82, 'ГОЛ (GOL Transportes Aereos)', '', 'G3', null),
                             (83, 'Гонконг Эйрлайнс (Hong Kong Airlines)', '', 'HX', null),
                             (84, 'Грозный Авиа (Grozny Avia)', '', 'ZG', null),
                             (85, 'Дарвин Эйрлайн (Darwin Airline)', '', 'F7', null),
                             (86, 'Дельта Эйрлайнс (Delta Airlines)', '', 'DL', null),
                             (87, 'Джат Эйрвэйс (Jat Airways)', '', 'JU', null),
                             (88, 'Джерманвингз (Germanwings)', '', '4U', null),
                             (89, 'Джет Эйрвэйс (Jet Airways)', '', '9W', null),
                             (90, 'Джет-ту.ком (Jet2.com)', '', 'LS', null),
                             (91, 'ДжетБлу Эйрвэйс (JetBlue Airways)', '', 'B6', null),
                             (92, 'Джетстар Азия (Jetstar Asia)', '', '3K', null),
                             (93, 'Джетстар Пасифик (Jetstar Pacific)', '', 'BL', null),
                             (94, 'Джетстар Эйрвейс (Jetstar Airways)', '', 'JQ', null),
                             (95, 'Джетэйрфлай (Jetairfly)', '', 'TB', null),
                             (96, 'Днеправиа (Dniproavia)', '', 'Z6', null),
                             (97, 'Добролет (Dobrolet)', '', 'QD', null),
                             (98, 'Добролет Плюс (Dobrolet Plus)', '', 'QD', null),
                             (99, 'Донавиа (Donavia)', '', 'D9', null),
                             (100, 'Донбассаэро (Donbassaero)', '', '7D', null),
                             (101, 'Драгонэйр (Dragonair)', '', 'KA', null),
                             (102, 'Евровингс (Eurowings)', '', 'EW', null),
                             (103, 'ЕвроЛОТ (EuroLOT)', '', 'K2', null),
                             (104, 'Еврофлай (Eurofly)', '', 'GJ', null),
                             (105, 'Египетские авиалинии (Egypt Air)', '', 'MS', null),
                             (106, 'Иберия (Iberia Airlines)', '', 'IB', null),
                             (107, 'Ижавиа (Izhavia)', '', 'I8', null),
                             (108, 'ИзиДжет (EasyJet)', '', 'U2', null),
                             (109, 'Изрэйр Эйрлайнс (Israir Airlines)', '', '6H', null),
                             (110, 'Икар (Ikar Airlines)', '', 'IK', null),
                             (111, 'Индиго Эйрлайнс (IndiGo Airlines)', '', '6E', null),
                             (112, 'Интерджет (Interjet)', '', '4O', null),
                             (113, 'Иран Эйр (Iran Air)', '', 'IR', null),
                             (114, 'ИрАэро (Iraero)', '', '', null),
                             (115, 'Ист Эйр (East Air)', '', 'EG', null),
                             (116, 'Кавминводыавиа (Kavminvodyavia airlines)', '', 'KV', null),
                             (117, 'Казак Эйр (Qazaq Air)', '', 'IQ', null),
                             (118, 'Кам Эйр (Kam Air)', '', 'RQ', null),
                             (119, 'Камбоджа Ангкор Эйр (Cambodia Angkor Air)', '', 'K6', null),
                             (120, 'Карпатэйр (Carpatair)', '', 'V3', null),
                             (121, 'Катай Пасифик (Cathay Pacific Airways)', '', 'CX', null),
                             (122, 'Катарские авиалинии (Qatar Airways)', '', 'QR', null),
                             (123, 'Катэкавиа (Katekavia)', '', 'KTK', null),
                             (124, 'Кения Эйрвэйс (Kenya Airways)', '', 'KQ', null),
                             (125, 'Кипрские Авиалинии (Cyprus Airways)', '', 'CY', null),
                             (126, 'Китайские авиалинии (China Airlines)', '', 'CI', null),
                             (127, 'Китайские Восточные Авиалинии (China Eastern Airlines)', '', 'MU', null),
                             (128, 'Китайские Южные Авиалинии (China Southern Airlines)', '', 'CZ', null),
                             (129, 'Кликэйр (Clickair)', '', 'XG', null),
                             (130, 'КЛМ (KLM Airlines)', '', 'KL', null),
                             (131, 'Колавиа (Kolavia) Когалымавиа', '', '7K', null),
                             (132, 'Комиавиатранс (Komiaviatrans)', '', '', null),
                             (133, 'Кондор (Condor Airlines)', '', 'DE', null),
                             (134, 'Континентальные авиалинии (Continental Airlines)', '', 'CO', null),
                             (135, 'Копа Эйрлайнс (Copa Airlines)', '', 'CM', null),
                             (136, 'Кореан Эйр (Korean Air)', '', 'KE', null),
                             (137, 'Корендон Эйрлайнc (Corendon Airlines)', '', 'XC', null),
                             (138, 'КрасАвиа (KrasAvia)', '', '', null),
                             (139, 'Кроатиа Эйрлайнс (Croatia Airlines)', '', 'OU', null),
                             (140, 'Куантас Эйрвейз (Qantas Airways)', '', 'QF', null),
                             (141, 'Кубана де Авиасьон (Cubana de Aviacion)', '', 'CU', null),
                             (142, 'Кубань (Kuban Airlines)', '', 'GW', null),
                             (143, 'Лайн Эйр (Lion Air)', '', 'JT', null),
                             (144, 'ЛАН Эйрлайнс (LAN Airlines)', '', 'LA', null),
                             (145, 'Ливингстон (Livingston)', '', 'JN', null),
                             (146, 'ЛОТ Польские Авиалинии (LOT Polish Airlines)', '', 'LO', null),
                             (147, 'Люксэйр (Luxair)', '', 'LG', null),
                             (148, 'Люфтганза (Lufthansa Airlines)', '', 'LH', null),
                             (149, 'Малайзия Эйрлайнс (Malaysia Airlines)', '', 'MH', null),
                             (150, 'Малеев Венгерские Авиалинии (Malev Hungarian Airlines)', '', 'MA', null),
                             (151, 'Махан Эйр (Mahan Air)', '', 'W5', null),
                             (152, 'Международные Авиалинии Украины МАУ (Ukraine International Airlines)', '', 'PS', null),
                             (153, 'Меридиана флай (Meridiana fly)', '', 'IG', null),
                             (154, 'Метроджет (Metrojet)', '', '7K', null),
                             (155, 'Мидл Ист Эйрлайнс (Middle East Airlines - MEA)', '', 'ME', null),
                             (156, 'Мистраль Эйр (Mistral Air)', '', '7M', null),
                             (157, 'Монарх Эйрлайнс (Monarch Airlines)', '', 'ZB', null),
                             (158, 'Монгольские авиалинии МИАТ (Mongolian Airlines MIAT)', '', 'OM', null),
                             (159, 'Монтенегро Эйрлайнс (Montenegro Airlines)', '', 'YM', null),
                             (160, 'Московия (Moskovia Airlines)', '', '3R', null),
                             (161, 'Мотор Сич (Motor Sich Airlines)', '', 'M9', null),
                             (162, 'Мьянма Эйрвэйз Интернешнл (Myanma Airways International)', '', '8M', null),
                             (163, 'НИКИ (NIKI Luftfahrt)', '', 'HG', null),
                             (164, 'Нок Эйр (Nok Air)', '', 'DD', null),
                             (165, 'Норвегиан Эйр Шаттл (Norwegian Air Shuttle)', '', 'DY', null),
                             (166, 'Норвежские авиалинии (Norwegian Airlines)', '', 'SK', null),
                             (167, 'Нордавиа - региональные авиалинии (Nordavia – Regional Airlines)', '', '5N', null),
                             (168, 'Нордика (Nordica)', '', '', null),
                             (169, 'НордСтар (NordStar Airlines) Таймыр', '', 'Y7', null),
                             (170, 'Нортвест Эйрлайнс (Northwest Airlines)', '', 'NW', null),
                             (171, 'Нувелэйр Тунис (Nouvelair Tunisie)', '', 'BJ', null),
                             (172, 'Олимпик Эйр (Olympic Air)', '', 'OA', null),
                             (173, 'Олл Ниппон Эйрвэйс (ANA All Nippon Airways)', '', 'NH', null),
                             (174, 'Онур Эйр (Onur Air)', '', '8Q', null),
                             (175, 'Оренбургские авиалинии (OrenAir)', '', 'R2', null),
                             (176, 'Оренбуржье (Orenburzhye)', '', '', null),
                             (177, 'Ориент Тай Эйрлайнс (Orient Thai Airlines)', '', 'OX', null),
                             (178, 'ПАНХ (Panh Airlines)', '', '', null),
                             (179, 'Пегас Флай (Pegas Fly)', '', 'IK', null),
                             (180, 'Пегасус Азия (Pegasus Asia)', '', 'ZM', null),
                             (181, 'Пегасус Эйрлайнс (Pegasus Airlines)', '', 'PC', null),
                             (182, 'Пионер - региональные авиалинии (Pioneer)', '', '', null),
                             (183, 'Победа (Pobeda)', '', 'DP', null),
                             (184, 'Полет (Polet Airlines)', '', 'YQ', null),
                             (185, 'Полярные авиалинии (Polar Airlines)', '', '', null),
                             (186, 'Псковавиа (Pskovavia)', '', '', null),
                             (187, 'Райанэйр (Ryanair)', '', 'FR', null),
                             (188, 'Ред Вингс (Red Wings Airlines)', '', 'WZ', null),
                             (189, 'Роза Ветров (WINDROSE)', '', '7W', null),
                             (190, 'Ройал Бруней Эйрлайнз (Royal Brunei Airlines)', '', 'BI', null),
                             (191, 'Ройал Джорданиан Эйрлайнс (Royal Jordanian Airlines)', '', 'RJ', null),
                             (192, 'Ройал Эйр Марок (Royal Air Maroc)', '', 'AT', null),
                             (193, 'Россия (Rossiya Airlines)', '', 'FV', null),
                             (194, 'Роял Флайт (Royal Flight) Абакан-Авиа', '', '4R', null),
                             (195, 'Руслайн (RusLine)', '', '7R', null),
                             (196, 'С7 Сибирь (S7 Airlines)', '', 'S7', null),
                             (197, 'Саратовские авиалинии (Saratov Airlines)', '', '6W', null),
                             (198, 'САС - Скандинавские Авиалинии (SAS - Scandinavian Airlines)', '', 'SK', null),
                             (199, 'Сауз Африкан Эйрвэйс (South African Airways)', '', 'SA', null),
                             (200, 'Саузвест Эйрлайнс (Southwest Airlines)', '', 'WN', null),
                             (201, 'Сахалинские авиатрассы (Sat Airlines)', '', 'HZ', null),
                             (202, 'Свисс Эйр (Swiss International Airlines)', '', 'LX', null),
                             (203, 'Себу Пасифик (Cebu Pacific)', '', '5J', null),
                             (204, 'Северный ветер Норд винд (Nordwind Airlines)', '', 'N4', null),
                             (205, 'Северсталь (Severstal Avia)', '', 'D2', null),
                             (206, 'Силкэйр (Silkair)', '', 'MI', null),
                             (207, 'Сингапурские авиалинии (Singapore Airlines)', '', 'SQ', null),
                             (208, 'Сирийские Авиалинии (Syrian Arab Airlines)', '', 'RB', null),
                             (209, 'СитиДжет (CityJet)', '', 'WX', null),
                             (210, 'Скай Бишкек (Sky Bishkek)', '', 'GY', null),
                             (211, 'Скай Экспресс (Sky Express)', '', 'XW', null),
                             (212, 'СкайВест Эйрлайнс (SkyWest Airlines)', '', 'OO', null),
                             (213, 'Скаймарк Эйрлайнс (Skymark Airlines)', '', 'BC', null),
                             (214, 'Скат (Scat Airlines)', '', 'DV', null),
                             (215, 'Скут (Scoot Airlines)', '', 'TZ', null),
                             (216, 'Смарт Вингс (Smart Wings)', '', 'QS', null),
                             (217, 'Смолл Плэнет Эйрлайнс (Small Planet Airlines)', '', 'S5', null),
                             (218, 'Сомон Эйр (Somon Air)', '', '4J', null),
                             (219, 'Спирит Эйрлайнс (Spirit Airlines)', '', 'NK', null),
                             (220, 'Спринг Эйрлайнс (Spring Airlines)', '', '9C', null),
                             (221, 'Сычуаньские авиалинии (Sichuan Airlines)', '', '3U', null),
                             (222, 'Сямыньские авиалинии (Xiamen Airlines)', '', 'MF', null),
                             (223, 'Таджик Эйр (Tajik Air)', '', '7J', null),
                             (224, 'ТАЙ Смайл (THAI Smile Airways)', '', 'TG', null),
                             (225, 'Тайгер Эйрвейз (Tiger Airways)', '', 'TR', null),
                             (226, 'Тайские авиалинии (Thai Airways)', '', 'TG', null),
                             (227, 'ТАМ Эйрланз (TAM Airlines)', '', 'JJ', null),
                             (228, 'ТАП Португал (TAP Portugal)', '', 'TP', null),
                             (229, 'Таром (Tarom)', '', 'RO', null),
                             (230, 'Татарстан (Tatarstan Airlines)', '', 'U9', null),
                             (231, 'Тирольские Авиалинии (Tyrolean Airways)', '', 'VO', null),
                             (232, 'Томас Кук Эйрлайнс (Thomas Cook Airlines)', '', 'MT', null),
                             (233, 'Томск Авиа (Tomsk Avia)', '', '', null),
                             (234, 'Томсонфлай (Thomsonfly)', '', 'BY', null),
                             (235, 'Трансавиа Эйрлайнс (Transavia Airlines)', '', 'HV', null),
                             (236, 'Трансаэро (Transaero Airlines)', '', 'UN', null),
                             (237, 'Трэвел Сервис Эйрлайнз (Travel Service Airlines)', '', 'QS', null),
                             (238, 'ТУИфлай (TUIfly)', '', 'X3', null),
                             (239, 'Тулпар Эйр (Tulpar Air)', '', '', null),
                             (240, 'Тунисэйр (Tunisair)', '', 'TU', null),
                             (241, 'Турецкие авиалинии (Turkish Airlines)', '', 'TK', null),
                             (242, 'Туркменские авиалинии (Turkmenistan Airlines)', '', 'T5', null),
                             (243, 'Узбекские авиалинии (Uzbekistan Airways)', '', 'HY', null),
                             (244, 'Украинско-Средиземноморские Авиалинии (UM Air)', '', 'UF', null),
                             (245, 'Уральские Авиалинии (Ural Airlines)', '', 'U6', null),
                             (246, 'Фиджи Эйрвэйс (Fiji Airways)', '', 'FJ', null),
                             (247, 'Филиппинские авиалинии (Philippine Airlines)', '', 'PR', null),
                             (248, 'Финнэйр (Finnair)', '', 'AY', null),
                             (249, 'Флай Ван (Fly One)', '', '5F', null),
                             (250, 'Флай Ван Армения (FlyOne Armenia)', '', '3F', null),
                             (251, 'Флай Виста (Fly Vista)', '', 'GT', null),
                             (252, 'Флай Дубай (Flydubai)', '', 'FZ', null),
                             (253, 'Флайби (Flybe)', '', 'BE', null),
                             (254, 'Хабаровские авиалинии ХабАвиа (Khabarovsk Airlines)', '', '', null),
                             (255, 'Хайнань Эйрлайнс (Hainan Airlines)', '', 'HU', null),
                             (256, 'Хахн Эйр (Hahn Air)', '', 'HR', null),
                             (257, 'Хоп! (HOP!)', '', 'A5', null),
                             (258, 'Центр-Юг (Center South)', '', 'DF', null),
                             (259, 'Чешские авиалинии (CSA Czech Airlines)', '', 'OK', null),
                             (260, 'Чукотавиа (Chukotavia)', '', '', null),
                             (261, 'Шанхайские авиалинии (Shanghai Airlines)', '', 'FM', null),
                             (262, 'Эва Эйр (Eva Air )', '', 'BR', null),
                             (263, 'Эгейские Авиалинии (Aegean Airlines)', '', 'A3', null),
                             (264, 'Эгль Азюр (Aigle Azur)', '', 'ZI', null),
                             (265, 'Эйр Азия (AirAsia)', '', 'AK', null),
                             (266, 'Эйр Алжир (Air Algerie)', '', 'AH', null),
                             (267, 'Эйр Арабия (Air Arabia)', '', 'G9', null),
                             (268, 'Эйр Армения (Air Armenia)', '', 'QN', null),
                             (269, 'Эйр Астана (Air Astana)', '', 'KC', null),
                             (270, 'Эйр Балтик (AirBaltic)', '', 'BT', null),
                             (271, 'Эйр Берлин (Air Berlin)', '', 'AB', null),
                             (272, 'Эйр Бишкек (Air Bishkek)', '', 'KR', null),
                             (273, 'Эйр Ван (Air One)', '', 'AP', null),
                             (274, 'Эйр Доломити (Air Dolomiti)', '', 'EN', null),
                             (275, 'Эйр Европа (Air Europa)', '', 'UX', null),
                             (276, 'Эйр Индия (Air India)', '', 'AI', null),
                             (277, 'Эйр Казахстан (Air Kazakhstan)', '', '9Y', null),
                             (278, 'Эйр Канада (Air Canada)', '', 'AC', null),
                             (279, 'Эйр Карибез (Air Caraibes)', '', 'TX', null),
                             (280, 'Эйр Корё (Air Koryo)', '', 'JS', null),
                             (281, 'Эйр Корсика (Air Corsica)', '', 'XK', null),
                             (282, 'Эйр Кыргызстан (Air Kyrgyzstan)', '', 'QH', null),
                             (283, 'Эйр Литуаника (Air Lituanica)', '', 'LT', null),
                             (284, 'Эйр Маврикий (Air Mauritius)', '', 'MK', null),
                             (285, 'Эйр Мальта (Air Malta)', '', 'KM', null),
                             (286, 'Эйр Манас (Air Manas)', '', 'ZM', null),
                             (287, 'Эйр Молдова (Air Moldova)', '', '9U', null),
                             (288, 'Эйр Намибия (Air Namibia)', '', 'SW', null),
                             (289, 'Эйр Нью Зеланд (Air New Zealand)', '', 'NZ', null),
                             (290, 'Эйр Оникс (Air Onix)', '', 'OG', null),
                             (291, 'Эйр Острал (Air Austral)', '', 'UU', null),
                             (292, 'Эйр Самара (Air Samara)', '', 'E5', null),
                             (293, 'Эйр Сейшелс (Air Seychelles)', '', 'HM', null),
                             (294, 'Эйр Сербия (Air Serbia)', '', 'JU', null),
                             (295, 'Эйр Франс (Air France)', '', 'AF', null),
                             (296, 'Эйр Чайна (Air China)', '', 'CA', null),
                             (297, 'ЭйрАзия Икс (AirAsia X)', '', 'D7', null),
                             (298, 'Эйрзена - Грузинские авиалинии (Airzena - Georgian Airways)', '', 'A9', null),
                             (299, 'Эллинэйр (Ellinair)', '', 'EL', null),
                             (300, 'Эль Аль Израильские авиалинии (El Al Israel Airlines)', '', 'LY', null),
                             (301, 'Эмирейтс (Emirates Airlines)', '', 'EK', null),
                             (302, 'Энтер Эйр (Enter Air)', '', 'E4', null),
                             (303, 'Эстониан Эйр (Estonian Air)', '', 'OV', null),
                             (304, 'Этихад Эйрвейз (Etihad Airways)', '', 'EY', null),
                             (305, 'Эфиопиан Эйрлайнс (Ethiopian Airlines)', '', 'ET', null),
                             (306, 'ЮВТ Аэро (UVT Aero)', '', 'UW', null),
                             (307, 'Юнайтед Эйрлайнс (United Airlines)', '', 'UA', null),
                             (308, 'ЮС Эйрвейз (US Airways)', '', 'US', null),
                             (309, 'ЮТэйр (UTair)', '', 'UT', null),
                             (310, 'ЮТэйр Украина (UTair Ukraine)', '', 'QU', null),
                             (311, 'ЮТэйр-Экспресс (UTair-Express)', '', 'UR', null),
                             (312, 'Якутия (Yakutia Airlines)', '', 'R3', null),
                             (313, 'Ямал (Yamal Airlines)', '', 'YL', null),
                             (314, 'ЯнЭйр (YanAir)', '', 'YE', null),
                             (315, 'Японские авиалинии - ДЖАЛ (Japan Airlines - JAL)', '', null);

